USE [master]
GO

/****** Object:  Database [Apartment] ***/
/*** Check and make sure you check "FILENAME" which is the PATH to store your data files. 
That should be the only changes needed
***/


CREATE DATABASE [Apartment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Apartment', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Apartment.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Apartment_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Apartment_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Apartment] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Apartment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Apartment] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Apartment] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Apartment] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Apartment] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Apartment] SET ARITHABORT OFF 
GO

ALTER DATABASE [Apartment] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Apartment] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Apartment] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Apartment] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Apartment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Apartment] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Apartment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Apartment] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Apartment] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Apartment] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Apartment] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Apartment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Apartment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Apartment] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Apartment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Apartment] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Apartment] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Apartment] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Apartment] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Apartment] SET  MULTI_USER 
GO

ALTER DATABASE [Apartment] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Apartment] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Apartment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Apartment] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Apartment] SET  READ_WRITE 
GO
